### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jincy7** [Jincy7/intern-match-with#2]
# 기능 요약

> 공통 기능

- [ ] 공고 검색하기

> 회사 회원 기능

- [ ] 인턴 공고 등록하기
- [ ] 인턴 합/불 통보하기

> 학생 회원 기능

- [ ] 인턴 공고 지원하기
- [ ] 인턴 최종 매칭 확인하기

**시나리오** : 

회사 로그인 -> 인턴 공고 등록 -> 

학생 로그인 -> 인턴 공고 검색 -> 인턴 지원 -> 

회사 로그인 -> 공고 검색 -> 인턴 합불 통보 -> 

학생 로그인 -> 인턴 최종 매칭 확인

**Comment by Jincy7** [comment]
**시나리오 업데이트**

정호 로그인 -> 네이버 인턴 공고 검색 -> 인턴 지원 ->

회사 로그인 -> 지원 현황 확인 -> 인턴 합불 통보 ->

정호 로그인 -> 인턴 최종 매칭 확인
